### ISSUE TITLE
SoundInfo.GetSoundLength returns 0

### ISSUE THREAD

**Issue by C485** [Davuskus/elevator-music-vs#3]
It return 0 for any wav file on my pc.

`            byte[] TotalBytes = File.ReadAllBytes(fileName);
            var bitrate = (BitConverter.ToInt32(new[] { TotalBytes[28], TotalBytes[29], TotalBytes[30], TotalBytes[31] }, 0) * 8);
            return (TotalBytes.Length - 8) * 8 / bitrate;`

this code works (from same thread on stack)

**Comment by C485** [comment]
Ofc, this code returns length in seconds not ms.

**Comment by david98hall** [comment]
Weird that it returned 0, it worked for me at least. I made some changes anyway to the SoundInfo class. Could you try again?
